spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/boot_book?characterEncoding=utf-8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: Asia/Shanghai

  main:
      allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true


logging:
  level:
    cn.bookmanager.mapper: DEBUG

mybatis:
  type-aliases-package: cn.bookmanager.entity
  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: true

server:
  port: 8081


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql