spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/boot_book?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
